apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-scaleobjects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rumstead/keda-playground.git'
    path: deploy/keda-objects
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
