apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-30T22:08:33Z"
  labels:
    app: keda-playground
  name: keda-playground
  namespace: default
  uid: cabbbc3d-0343-46ce-ac29-98e4bf88c01b
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 6000-6000
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: keda-playground
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
