apiVersion: v1
kind: Service
metadata:
  labels:
    app: keda-playground
  name: keda-playground
  namespace: default
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: keda-playground
  type: ClusterIP
