apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: deploy-one
  namespace: default
spec:
  scaleTargetRef:
#    apiVersion:    {api-version-of-target-resource}  # Optional. Default: apps/v1
#    kind:          {kind-of-target-resource}         # Optional. Default: Deployment
    name: app-one                  # Mandatory. Must be in the same namespace as the ScaledObject
#    envSourceContainerName: {container-name}         # Optional. Default: .spec.template.spec.containers[0]
  pollingInterval:  30                               # Optional. Default: 30 seconds
  cooldownPeriod:   300                              # Optional. Default: 300 seconds
#  idleReplicaCount: 0                                # Optional. Default: ignored, must be less than minReplicaCount
  minReplicaCount:  0                                # Optional. Default: 0
#  maxReplicaCount:  5                                # Optional. Default: 100
  triggers:
    - type: metric-api
      metadata:
        targetValue: "5"
        url: "keda-playground.default.svc.cluster.local:8080/scale"
        valueLocation: "replicas"