apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - name: app-two
          image: busybox
          imagePullPolicy: Never
          args:
            - sleep
            - infinity
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP